[tool.poetry]
name = "unsplash-iterable-dataset"
version = "0.1.0"
description = ""
authors = ["oelin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
datasets = "^2.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
